site_name: Spec Classes
pages:
  - Introduction: index.md
  - Examples:
    - Overview: examples/index.md
    - Basic: examples/basic.md
    - Collections: examples/collections.md
    - Dataclass Interoperability: examples/dataclasses.md
    - Preparation/Typecasting: examples/preparation.md
  - Usage:
    - Overview: usage/index.md
    - Basic Usage: usage/basic.md
    - Helper Methods:
      - Overview: usage/methods/index.md
      - Toplevel Methods: usage/methods/toplevel.md
      - Scalar Methods: usage/methods/scalars.md
      - Collection Methods: usage/methods/collections.md
    - Special Types: usage/special_types.md
    - Advanced Usage: usage/advanced.md
  - Implementation Details:
    - How It Works: implementation/how_it_works.md
    - Performance Implications: implementation/performance.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.integrate
  logo: assets/images/logo.svg
extra_css:
  - assets/stylesheets/colors.css
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences